INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Bits n Bytes','bits_n_bytes');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Chem Udaan',		'chem_udaan');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Circuitrix',		'circuitrix');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('City Smart',		'city_smart');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Codemasters',		'codemasters');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Contraption',		'contraption');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Cooling Tower Design','cooling_tower_design');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Crossfire',				'crossfire');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Elcectic Car',		'elcectic_car');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Free Energy Genrator','free_energy_genrator');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Jal Shudhta',		'jal_shudhta');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Logo Fad',					 'logo_fad');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Magtag Lifting',	'magtag_lifting');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Modship',				'modship');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Reverse Engineering','reverse_engineering');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Techniker Wizard',	'techniker_wizard');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('The Estimator',		'the_estimator');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Trust Thy Bridge',	'trust_thy_bridge');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Chemical Treasure Hunt','chemical_treasure_hunt');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Element 15','element_15');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Junkyard','junkyard');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Krati vkrati','krati_vkrati');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Mag Tech Lifting','mag_tech_lifting');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Oscilloscope Drawing','oscilloscope_drawing');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Push_the_code','push_the_code');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Robomagellan','robomagellan');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Robothone','robothone');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Tech Teaser','tech_teaser');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Smart City Challange','smart_city_challange');
INSERT INTO `bogie`.`events` (`name`, `view_name`) VALUES ('Edge Over','edge_over');
